# Generated by Django 5.0.6 on 2025-10-10 10:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200, unique=True)),
                ('seed_keyword', models.CharField(max_length=300)),
                ('title_count', models.PositiveIntegerField(default=10)),
                ('suggest_count', models.PositiveIntegerField(default=20)),
                ('desc_length', models.PositiveIntegerField(default=200)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=64, unique=True)),
                ('openai_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('youtube_api_key', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FileItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('tags', models.TextField(blank=True, default='')),
                ('is_used', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.filebatch')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slots', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('selection_mode', models.CharField(default='random', max_length=16)),
                ('deadline_minutes', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(60)])),
                ('price_per_item', models.DecimalField(decimal_places=2, default=10.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('video_zip', models.FileField(upload_to='videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='core.filebatch')),
            ],
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('tags', models.TextField()),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('file_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='core.fileitem')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.work')),
            ],
        ),
    ]
