# Generated by Django 5.0.6 on 2025-10-10 16:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='slots',
            new_name='total_slots',
        ),
        migrations.RemoveField(
            model_name='work',
            name='selection_mode',
        ),
        migrations.AddField(
            model_name='fileitem',
            name='reuse_limit',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='fileitem',
            name='used_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='work',
            name='remaining_slots',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='WorkClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('tags', models.TextField()),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('claimed', 'claimed'), ('submitted', 'submitted'), ('expired', 'expired'), ('approved', 'approved'), ('rejected', 'rejected')], default='claimed', max_length=16)),
                ('client_id', models.CharField(blank=True, default='', max_length=100)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, default='')),
                ('file_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='core.fileitem')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.work')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkItem',
        ),
    ]
