# Generated by Django 5.0.6 on 2025-10-11 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_workclaim_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workclaim',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workclaim',
            name='status',
            field=models.CharField(choices=[('claimed', 'Claimed'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='claimed', max_length=16),
        ),
        migrations.AlterField(
            model_name='workclaim',
            name='title',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='workclaim',
            constraint=models.UniqueConstraint(fields=('work', 'user'), name='uniq_work_per_user'),
        ),
    ]
