# Generated by Django 5.0.6 on 2025-10-12 19:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_workclaim_expires_at_alter_workclaim_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimMetricsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('likes', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-snapshot_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('task_credit', 'Task Credit'), ('milestone_bonus', 'Milestone Bonus'), ('withdrawal_hold', 'Withdrawal Hold'), ('withdrawal', 'Withdrawal Payout'), ('admin_adjustment', 'Admin Adjustment'), ('reversal', 'Reversal')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('upi_vpa', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='workclaim',
            name='uniq_work_per_user',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='name',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='min_withdraw_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='rate_per_1000_views',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workclaim',
            name='next_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workclaim',
            name='review_status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=20),
        ),
        migrations.AddField(
            model_name='workclaim',
            name='views_paid_units',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workclaim',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='workclaim',
            name='yt_last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workclaim',
            name='yt_likes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workclaim',
            name='yt_views',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filebatch',
            name='desc_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filebatch',
            name='file_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='filebatch',
            name='seed_keyword',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='filebatch',
            name='suggest_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filebatch',
            name='suggestions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='filebatch',
            name='title_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fileitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fileitem',
            name='reuse_limit',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='fileitem',
            name='tags',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fileitem',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fileitem',
            name='used_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='deadline_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='work',
            name='file_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='core.filebatch'),
        ),
        migrations.AlterField(
            model_name='work',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='work',
            name='remaining_slots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='total_slots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='video_zip',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='workclaim',
            name='client_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='workclaim',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workclaim',
            name='file_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fileitem'),
        ),
        migrations.AlterField(
            model_name='workclaim',
            name='status',
            field=models.CharField(choices=[('claimed', 'Claimed'), ('submitted', 'Submitted'), ('expired', 'Expired')], default='claimed', max_length=20),
        ),
        migrations.AlterField(
            model_name='workclaim',
            name='tags',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workclaim',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workclaim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workclaim',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='claimmetricslog',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_log', to='core.workclaim'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='ref_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workclaim'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.wallet'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='core.wallet'),
        ),
    ]
