# Generated by Django 5.0.6 on 2025-10-13 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_claimmetricslog_wallet_wallettransaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workclaim',
            constraint=models.UniqueConstraint(fields=('user', 'work'), name='uniq_user_work'),
        ),
    ]
