# Generated by Django 5.2.7 on 2025-10-17 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_workclaim_uniq_user_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('threshold_views', models.PositiveBigIntegerField(unique=True)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['threshold_views'],
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='min_withdraw_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.CreateModel(
            name='MilestonePayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_snapshot', models.PositiveBigIntegerField(default=0)),
                ('likes_snapshot', models.PositiveBigIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_payouts', to='core.workclaim')),
                ('credited_txn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.wallettransaction')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_hits', to='core.milestonerule')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('claim', 'rule'), name='uniq_claim_rule_once')],
            },
        ),
    ]
